### ISSUE TITLE
Determine impact of contract deployment in fees

### ISSUE THREAD

**Issue by eloylp** [eigerco/nebula#25]
### Context

Initially we were influenced by [this](https://ethereum.stackexchange.com/questions/29621/is-better-to-use-a-single-smart-contract-or-one-for-each-bet), but thats for Ethereum. Stellar is a different, more modern technology that could not have the same fee problems.

See more about fees [here](https://soroban.stellar.org/docs/fundamentals-and-concepts/fees-and-metering).

### Goals

* To better understand how [fees](https://soroban.stellar.org/docs/fundamentals-and-concepts/fees-and-metering) works regarding deployment of smart contracts in Soroban. 
* Might be good to do some experiments in Futurenet, like we did [here](https://github.com/eigerco/nebula/issues/5#issuecomment-1645208546) and document outputs.
* Also we could use channels like Discord for more information gathering.
* Investigate the metering tools, like the [pre-flight service](https://soroban.stellar.org/docs/fundamentals-and-concepts/interacting-with-contracts#preflight).

**Comment by geofmureithi** [comment]
You should be able to calculate this using:

```
soroban invoke \
  --wasm target/wasm32-unknown-unknown/release/project.wasm \
  --id 1 \
  --fn add \
  --arg 1 \
  --arg 2 \
  --cost \
  --footprint
```

**Comment by eloylp** [comment]
Alright ! i am taking over this. Lets try that tools with one of our contracts and log here results.

**Comment by eloylp** [comment]
Ok , for the [current voting contract](https://github.com/eigerco/nebula/tree/22a9cc3b90a5e624dc06dcfc2780fac7eb5763f4/contracts/voting), i repeated the `init` and `create_proposal` steps in futurenet, like we did in previous [futurenet tests](https://github.com/eigerco/nebula/issues/5#issuecomment-1645208546). 

Then i searched on [the laboratory](https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=for_account&values=eyJvcmRlciI6ImRlc2MiLCJhY2NvdW50X2lkIjoiR0QyT1RPMjc1Q09MRDVLWUlHNkJYSjRQVExRNjNNWllFNE02T0RRWDdPNjdaRk82SlFDVlZOVEwiLCJpbmNsdWRlX2ZhaWxlZCI6ImZhbHNlIn0%3D&network=futurenet) for the `fee_charged` values. Here are the results:

* Contract deployment (wasm upload) - `43_197` stroops.
* `init` - `240_180` stroops.
* `create_proposal` - `109_294` stroops.

Looks like contract deployment in soroban is relatively cheap ! however,  i would like to repeat this test multiple times, just check this results are more or less deterministic. 

### Next steps

* Repeat the tests to ensure they are more or less deterministic.
* Build a simplified version of the voting example contract.  In such version, only one proposal/contract can be voted. So it would a single use contract.
* Repeat the same fee over the simplified version of the contract.

**Comment by eloylp** [comment]
### Repeating tests

* Contract deployment (wasm upload) (`hostFunction: [hostFunctionTypeUploadContractWasm]`) - `66_251` stroops.
* Contract creation (`hostFunction: [hostFunctionTypeCreateContract]`) - `43_462` stroops.

Deploying a contract involves the 2 trasactions  listed above. We missed this fact part in [previous tests](https://github.com/eigerco/nebula/issues/25#issuecomment-1665846370) and taking into account both operations for the `voting` contract means `109_713`  stroops.

Contract functions:

* init - `240_180` stroops.
* create_proposal - `109_717` stroops.

Conclusions:

* Fees are more or less predictable comparing with the previous tests, which makes sense taking into account how [they are measured](https://soroban.stellar.org/docs/fundamentals-and-concepts/fees-and-metering).
* Initial operations (`hostFunctionTypeUploadContractWasm`, `hostFunctionTypeCreateContract`) for uploading and activating the contract are relatively cheap.
* Its still a valid question if a simpler design 1 contract for each proposal could be cheaper.

**Comment by eloylp** [comment]
### Tests for simplified version of voting contract

Created a simplified version of the contract, that only allows one proposal per contract: https://github.com/eigerco/nebula/pull/39

* Contract deployment (wasm upload) (`hostFunction: [hostFunctionTypeUploadContractWasm]`) - `52_795` stroops.
* Contract creation (`hostFunction: [hostFunctionTypeCreateContract]`) - `41_169` stroops.

Taking into account both operations for the `voting` contract means `93_964`  stroops.

Contract functions:

* init - `103_196` stroops. This includes the proposal creation.

**Comment by eloylp** [comment]
### Conclusions

We are comparing here the previous tests:

1. [For the contract that accepts multiple proposals](https://github.com/eigerco/nebula/issues/25#issuecomment-1686607999).
2. [For the contract that only accepts one proposal](https://github.com/eigerco/nebula/issues/25#issuecomment-1686798138).

Once we have the contract `1` deployed and initialized, creating a new proposal sums a total of  `109_717` stroops. In `2` , deploying each contract/proposal ready to vote sums a total of  `197_160` stroops. Near the double. Makes sense as in `2` we are paying intialiasation per each proposal/contract.

We can conclude the use case can clearly determine what approach is better. If one is only interested in a single proposal and doesnt plan to create thousands probably could go for `2` , as it would be similar in terms of costs. But if the plan is to create multiple proposals `1` should be the way to go as it only pays wasm upload and intialisation once.

**Comment by mariopil** [comment]
How do you calculate fees? Is it possible now with latest soroban, or have you calculated it with laboratory only?

**Comment by geofmureithi** [comment]
What do you think would be the next steps here?

**Comment by eloylp** [comment]
> What do you think would be the next steps here? Do you need any help?

* Unless any of you detect a possible deficiency in the investigation done, close this issue. From my POV all the initial proposed goals were achieved. Let me know :) 

* I would like to get a review in #39 (early feedback)

* We could decide what to do with #39. That contract was generated during this research issue. But, we can also wait for #26 , as there are some interesting things to test. I would go for this last one.
