### ISSUE TITLE
Research yield bearing instruments

### ISSUE THREAD

**Issue by eloylp** [eigerco/nebula#37]
### Context

Some possibly interesting information to review:

* https://developers.stellar.org/docs/encyclopedia/liquidity-on-stellar-sdex-liquidity-pools
* https://developers.stellar.org/docs/encyclopedia/sponsored-reserves
* https://developers.stellar.org/docs/encyclopedia/claimable-balances
* https://soroban.stellar.org/docs/advanced-tutorials/liquidity-pool

Review [the list](https://airtable.com/app8gFatSkJVeufqN/shru3WQKCz7AfWhdV/tblvjmvad2hL4R8EZ) of community projects.

### Goal

* Do some preliminary research on how to build yield bearing instruments.
* Document our knowledge publicly.

**Comment by mariopil** [comment]
Stellar network has support for liquid pools and claimable balances - their SDK fully supports it [here](https://developers.stellar.org/docs/encyclopedia/liquidity-on-stellar-sdex-liquidity-pools) and [here](https://developers.stellar.org/docs/encyclopedia/claimable-balances). There are also example contract implementations available in Soroban (`timelock` and `liquidity_pool` examples) but they don't use anything from the Stellar SDK. If we would like to implement some contracts for e.g. liquid pools with AMM we would have to do it from scratch but we can use existing examples as a base. 

We would also need a Token contract implemented, as that would be used for liquid pool share token creation. 

There is existing project that implements AMM: https://github.com/soroswap - it contains a lot of contracts in core which might be also useful. They've also implemented UI for fully working AMM.
