### ISSUE TITLE
Describe the layout and content to be used in Nebula

### ISSUE THREAD

**Issue by geofmureithi** [eigerco/nebula#43]
Currently, we just have an about us and the wizard.
I am expecting the website will have more content: 
- /docs/ for documentation about contracts provided, eg https://soroban.stellar.org/docs/advanced-tutorials/tokens
- /audit/ information about audits of the contract
- ....

**Comment by geofmureithi** [comment]
Related to #24 
@eloylp Does this clear up the content question?

**Comment by geofmureithi** [comment]
I am not sure but it could be something like: `/audit/reports/voting.md`
The point is we can now be able to create new pages by just adding a new markdown file.
I may not know the specific pages but the idea is we make routing file based rather than code based.

**Comment by eloylp** [comment]
Great to be able to write markdown ! :heavy_plus_sign:
