### ISSUE TITLE
Prepare contract documentation template

### ISSUE THREAD

**Issue by geofmureithi** [eigerco/nebula#62]
Here is what I have:
_______________________
# Contract Title

Some detailed description of the contract

## Features
Basic list of the specific features.
Eg: [insert lottery example link]

## Importing with nebula-importer

````toml
[package.metadata.nebula.imports]
<contract-name> = <contract_url>
````
### Initialize the contract
```
Some code here
```
To call this code:
```
soroban-cli ...
```

### Perfom action 1
This is a very important step
```
Some code here
```
To call this code:
```
soroban-cli ...
```

### Perfom action 2
This is a very important step
```
Some code here
```
To call this code:
```
soroban-cli ...
```

### Cleaning up?

You may need to clean up

## Conclusion

Some conclusion goes here.

## Learn more
Link 1

Link 2

**Comment by mariopil** [comment]
Maybe also add a list of all contract methods somewhere in the beginning, e.g. after the `Importing...` paragraph? Just a short list - method name + short description. More details would be in separate points under the `Using the contract` paragraph.

**Comment by geofmureithi** [comment]
Usually this is generated from H2 tags in markdown
