### ISSUE TITLE
It's possible to buy tickets after raffle is played in Raffle contract

### ISSUE THREAD

**Issue by mariopil** [eigerco/nebula#64]
After the `play_raffle` method is invoked it should not be possible to buy any new tickets.

**Comment by eloylp** [comment]
Thanks for this. We need a similar check like [this one ](https://github.com/eigerco/nebula/blob/main/contracts/raffle/src/lib.rs#L168-L170) .

It would be good to extract that check to its own function probably, in order to increase readability.
