### ISSUE TITLE
Add more validations in voting contract init methods

### ISSUE THREAD

**Issue by eloylp** [eigerco/nebula#67]
**Describe the bug**

Some validations are not present in [init](https://github.com/eigerco/nebula/blob/main/contracts/voting/src/lib.rs#L78-L84) function of the voting contract. Parameters like `voting_period_secs`, `target_approval_rate_bps` and `total_voters` should never be zero.

**Comment by mariopil** [comment]
Completed with https://github.com/eigerco/nebula/pull/92
