### ISSUE TITLE
Improvements in the CI

### ISSUE THREAD

**Issue by eloylp** [eigerco/nebula#68]
**Is your feature request related to a problem? Please describe.**

When we are pushing commits in PRs, we are also updating the wasm contracts artifacts repository, which is not ideal, as contracts in PRs are still not approved, thus not reliable.

**Describe the solution you'd like**

To clearly separate both CI flows, `pull request to main`  and `merge to main` . To only upload contract artifacts when the code is **merged** in the `main` branch. 

**Describe alternatives you've considered**

Currently the [CI](https://github.com/eigerco/nebula/blob/main/.github/workflows/contracts.yml#L3-L6) code follows this directive:

`pr.yml`
```yaml
on:
  push:
  pull_request:
    branches: ["main"]
```

We could leave the above for PRs and create an new workflow exclusive for when we merge in `main` branch:

`main.yml`
```yaml
on:
  push:
    branches: ["main"]
```

Some steps would need to be shared among the 2 flows. Like the testing things. In order to avoid such duplication, we could make use of [github reusable workflows](https://docs.github.com/es/actions/using-workflows/reusing-workflows).

**Additional context**

We could check this [other project CI](https://github.com/eigerco/uniffi-zcash-lib/tree/main/.github/workflows) for inspiration.

**Comment by geofmureithi** [comment]
These changes are already in the #7 because I had to breakdown artifacts
