### ISSUE TITLE
Voting contract is build for every other contract

### ISSUE THREAD

**Issue by geofmureithi** [eigerco/nebula#88]
The current entry for building contracts has this line.

https://github.com/eigerco/nebula/blob/6b30196dc4a9eade2674e58e10bb7716bb7908ba/.github/workflows/contracts.yml#L40

The voting contract is only needed for governance contract.

**Comment by eloylp** [comment]
Currently, the Governance contract needs the voting contract as a dependency. How we could specify a build order ? I am trying to think in alternatives, as i think having a contract that depends in another one, is a pattern we are going to face again in the future.

**Comment by eloylp** [comment]
Is this already fixed ?

**Comment by geofmureithi** [comment]
Yes inside the matrix
https://github.com/eigerco/nebula/blob/99d21145b4de9fff17603ed31554fd3111b17084/.github/workflows/contracts.yml#L41

**Comment by eloylp** [comment]
Okay, closing it.

**Comment by geofmureithi** [comment]
But its not solved?
