### ISSUE TITLE
Contract issues

### ISSUE THREAD

**Issue by geofmureithi** [eigerco/nebula#98]
- [ ] Missing OCI sync
- [ ] Missing OCI imports

**Comment by geofmureithi** [comment]
These require a release.

**Comment by geofmureithi** [comment]
@eloylp once you do a release, this will be deployed.

**Comment by eloylp** [comment]
> @eloylp once you do a release, these will be deployed.

Release done. Closing this. Re-open if necessary. 

https://github.com/eigerco/nebula/releases/tag/v0.2.0
